# Contacts TUI Configuration

[database]
# Path to the SQLite database file
# Default: ~/.config/contacts/contacts.db
# 
# You can use ~ for home directory expansion
# Examples:
#   path = "~/Dropbox/contacts/contacts.db"
#   path = "/mnt/shared/contacts.db"
#   path = "~/Documents/contacts.db"
path = "~/.config/contacts/contacts.db"

[tasks]
# Task management backend to use
# Options: "taskwarrior", "dstask", "things", "none", or "" (empty for auto-detect)
# Default: "" (auto-detect in order: taskwarrior → dstask → things → none)
#
# Examples:
#   backend = "dstask"      # Force dstask even if taskwarrior is installed
#   backend = "taskwarrior" # Force taskwarrior
#   backend = "things"      # Force Things (macOS only)
#   backend = "none"        # Disable task integration
#   backend = ""            # Auto-detect (default)
backend = ""

[tasks.dstask]
# Dstask-specific configuration (only used when backend = "dstask")
# 
# Project to assign to all contact tasks
# Default: "contacts"
# project = "contacts"

[tasks.taskwarrior]
# TaskWarrior-specific configuration (only used when backend = "taskwarrior")
# 
# Project to assign to all contact tasks
# Default: "contacts"
# project = "contacts"

[tasks.things]
# Things-specific configuration (only used when backend = "things")
# 
# Auth token is REQUIRED for creating tasks
# Get it from: Things > Preferences > General > Enable Things URLs > Manage
# auth_token = "YOUR_AUTH_TOKEN_HERE"
#
# Optional: Default list for new tasks
# default_list = "Anytime"
#
# Optional: Tag template for contact tasks
# {state} and {label} will be replaced with actual values
# tag_template = "contact-{state}"

[external]
# External tool integrations
#
# Enable notes-tui integration (O key to open notes for contact)
# Default: false
# notes_tui = false
